language: python
python:
    - "3.6"
before_install:
    - cd project
    - sudo apt-get install libgnutls28-dev
install: "pip install -r requirements.txt"
script:
    - SECRET_KEY="Tr@v1$t3sT" python manage.py test
